name: applaudo_todo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  formz: ^0.4.1
  get_it: ^7.2.0
  go_router: ^6.0.9
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mocktail: ^0.3.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  syncfusion_flutter_datepicker: ^20.4.48

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

font:
  - family: 
    - Nunito Sans
    fonts: 
      - asset: assets/fonts/NunitoSans-Regular.ttf
        weight: 400
  - family: 
    - Poppins
    fonts: 
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
  - family:
    - Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400

